In [2]:
# Garrett Lawson, 2023
# MATH381

import random
import math
import numpy as np

class Player:
    
    def __init__(self, score):
        self.score = score

mynums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30] 

for row in mynums:
        
    print("------------------------------------------")
    print("Beta = " + str(row))
        
    WIN_SCORE = 30
    MAX_TURNS = 20

    numPlayers = 2 # Two player game. We could potentially change the game to include more than two
                    # players but the current code only supports two.
    numGames = 1000
    numTrials = 10

    Player0WRs = np.zeros(numTrials)
    tie = 0

    for trial in range(numTrials):

        wins = np.zeros(numPlayers)

        for game in range(numGames): # game loop

            ### initialize players
            players = []
            for i in range(numPlayers):
                players.append(Player(0))

            #### Start playing the game
            currentTurn = 1
            currentPlayer = game % numPlayers ### start with a different player each time
            #print("Scores: [0, 0]")
            while(currentTurn<=MAX_TURNS):

                # each player takes a turn
                # roll the die
                dieRoll = random.randint(1, 6)
                #print("Player " + str(currentPlayer) + " rolls a " + str(dieRoll))

                # Player either adds to their score or subtracts from opponent's score
                if (currentPlayer in [0]):
                    scoreBuffer = 4
                    scoreThresh = 6
                    # Strategy for this player: 
                    # Always add unless the opponent is at least scoreBuffer points ahead
                    # and adding the roll would not result in a win
                    if ((players[1].score>=(players[0].score+scoreBuffer) or 
                         players[1].score>=(WIN_SCORE-scoreThresh)) and players[0].score<WIN_SCORE-dieRoll):
                        if (players[1].score-dieRoll<0):
                            players[1].score=0
                        else:
                            players[1].score-=dieRoll
                    else:
                        players[0].score+=dieRoll

                if (currentPlayer in [1]):
                    scoreBuffer = WIN_SCORE # player 1 always adds
                    scoreThresh = 0
                    # Strategy for this player: 
                    # Always add unless the opponent is at least scoreBuffer points ahead
                    # and adding the roll would not result in a win
                    if ((players[0].score>=(players[1].score+scoreBuffer) or
                         players[0].score>=(WIN_SCORE-scoreThresh)) and players[1].score<WIN_SCORE-dieRoll):
                        if (players[0].score-dieRoll<0):
                            players[0].score=0
                        else:
                            players[0].score-=dieRoll
                    else:
                        players[1].score+=dieRoll

                # print the scores for each turn
                #print("Scores: [" + str(players[0].score) + ", " + str(players[1].score) + "]")

                # If the current player has reached the goal score, they win   
                if (players[currentPlayer].score>=WIN_SCORE):
                    wins[currentPlayer]+=1
                    #print("Player " + str(currentPlayer) + " wins!")
                    #print("Scores: [" + str(players[0].score) + ", " + str(players[1].score) + "]")
                    break
                elif (currentTurn==MAX_TURNS): # If we reach max turns, whoever has higher score wins
                    if (players[0].score>players[1].score):
                        wins[0]+=1
                    elif (players[1].score>players[0].score):
                        wins[1]+=1
                    else:
                        wins[0]+=0
                        wins[1]+=0
                        tie+=1
                    break

                # next turn
                currentPlayer = (currentPlayer+1) % numPlayers
                currentTurn += 1

            ## game is over

            # print win probability for player 0 every so often
            #if ((game % 10000==0) and (game>0)):
             #   print(wins[0]*1./game)

        ## output win percentage for all players
        """print("-------------------")
        print("Stats Over All Games")

        print(wins)        

        for i in range(numPlayers):
            print(i, " ", wins[i]*1./numGames)"""

        Player0WRs[trial] = wins[0]*1./numGames

    print(Player0WRs)
    print("Ties: " + str(round(tie*1./(numGames*numTrials), 3)))
    print("("+str(round(min(Player0WRs),3))+", "+str(round(max(Player0WRs),3))+")")
   

------------------------------------------
Beta = 1
[0.516 0.53  0.496 0.524 0.481 0.515 0.497 0.511 0.495 0.485]
Ties: 0.038
(0.481, 0.53)
------------------------------------------
Beta = 2
[0.521 0.488 0.51  0.5   0.504 0.476 0.494 0.502 0.499 0.493]
Ties: 0.037
(0.476, 0.521)
------------------------------------------
Beta = 3
[0.534 0.521 0.506 0.501 0.506 0.52  0.501 0.511 0.496 0.523]
Ties: 0.038
(0.496, 0.534)
------------------------------------------
Beta = 4
[0.527 0.486 0.462 0.515 0.507 0.489 0.504 0.518 0.496 0.553]
Ties: 0.04
(0.462, 0.553)
------------------------------------------
Beta = 5
[0.517 0.55  0.519 0.484 0.494 0.51  0.505 0.485 0.516 0.505]
Ties: 0.037
(0.484, 0.55)
------------------------------------------
Beta = 6
[0.511 0.505 0.513 0.515 0.55  0.518 0.534 0.501 0.521 0.537]
Ties: 0.034
(0.501, 0.55)
------------------------------------------
Beta = 7
[0.515 0.521 0.542 0.513 0.498 0.515 0.515 0.494 0.481 0.491]
Ties: 0.034
(0.481, 0.542)
-----------------